// 1. Define the ROYGBIV Palette (Same RGB values as your Node script)
const COLORS = {
    'Red': [187, 1, 0],
    'Orange': [255, 165, 0],
    'Yellow': [252, 222, 3],
    'Green': [2, 81, 2],
    'Blue': [0, 0, 255],
    'Indigo': [75, 0, 130],
    'Violet': [238, 130, 238]
  };
  
  // 2. Initialize Dropdowns
  const dropdowns = ['frameColor', 'toolbarColor', 'bgColor'];
  
  // Helper to populate a select element
  function populateSelect(elementId) {
    const select = document.getElementById(elementId);
    Object.keys(COLORS).forEach(colorName => {
      const option = document.createElement('option');
      option.value = colorName;
      option.textContent = colorName;
      select.appendChild(option);
    });
  }
  
  // Populate all three dropdowns
  dropdowns.forEach(populateSelect);
  
  // 3. Handle the "Confirm" Button
  document.getElementById('confirmBtn').addEventListener('click', () => {
    const themeName = document.getElementById('themeName').value || "My Custom Theme";
    
    // Get RGB arrays based on selection
    const frameRGB = COLORS[document.getElementById('frameColor').value];
    const toolbarRGB = COLORS[document.getElementById('toolbarColor').value];
    const bgRGB = COLORS[document.getElementById('bgColor').value];
  
    // Construct the Manifest Object
    // This is the exact JSON structure Chromium needs
    const manifest = {
      "manifest_version": 3,
      "version": "1.0",
      "name": themeName,
      "description": "Custom theme generated by extension.",
      "theme": {
        "colors": {
          "frame": frameRGB,
          "toolbar": toolbarRGB,
          "ntp_background": bgRGB,
          "ntp_text": [0, 0, 0],
          "tab_text": [0, 0, 0],
          "tab_background_text": [255, 255, 255],
          "button_background": toolbarRGB 
        }
      }
    };
  
    // 4. Create and Download the File
    const jsonString = JSON.stringify(manifest, null, 2);
    const blob = new Blob([jsonString], {type: "application/json"});
    const url = URL.createObjectURL(blob);
    
    // Create a temporary link to trigger the download
    // Note: Extensions cannot force the file into a specific folder automatically.
    // It will go to the user's default 'Downloads' folder.
    const a = document.createElement('a');
    a.href = url;
    a.download = "manifest.json"; 
    document.body.appendChild(a);
    a.click();
    
    // Cleanup
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  });